"""
FastAPI template strings for the generated api/app.py.

Used by `half_orm litestar generate --fastapi`.
Only auto-CRUD routes (CRUD_ACCESS) are supported; @api_* decorators are
Litestar-specific and are ignored in FastAPI mode.
"""

from half_orm_gen.backend.templates import CRUD_HELPERS, CRUD_MODULE_IMPORT

FRAMEWORK = 'fastapi'

HEADER = """\
# This file is generated by `half_orm litestar generate --fastapi`. Do not edit.
from typing import Optional, List, Any
import typing
import datetime
import uuid
import os
import sys
from contextlib import asynccontextmanager

cur_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, cur_dir)
par_dir = os.path.join(cur_dir, os.path.pardir)
sys.path.insert(0, par_dir)

from fastapi import FastAPI, APIRouter, HTTPException, Request, Path
from pydantic import BaseModel
from typing import Annotated

from {module} import ho_baseclasses
from {module} import ho_typeddicts
from {module} import MODEL

try:
    from api.custom.routes import router as _custom_router
    _has_custom = True
except ImportError:
    _has_custom = False

router = APIRouter()

"""

FOOTER = '''
_HO_WARN = """
======================================================================
  halfORM DEV HELPERS ACTIVE — NOT FOR PRODUCTION
======================================================================
  /ho_roles  : exposes all declared roles (no authentication)
  /ho_access : exposes the full access map filtered by role
  _get_roles : bearer token used directly as a role name
               (no signature verification)
  ho_dev     : super-role with full access to all resources
               (Authorization: Bearer ho_dev)

  Replace the Authorization middleware with a real JWT implementation
  before deploying to production.
======================================================================
"""

_HO_WARN_SHOWN = False

@asynccontextmanager
async def _ho_lifespan(app: FastAPI):
    global _HO_WARN_SHOWN
    import sys
    await MODEL.aconnect()
    if MODEL._production_mode:
        raise RuntimeError(
            "halfORM DEV HELPERS are active (ho_roles, ho_access, _get_roles fallback). "
            "These routes and the bearer-token-as-role fallback are not safe for production. "
            "Secure or remove them before deploying."
        )
    if not _HO_WARN_SHOWN:
        print(_HO_WARN, file=sys.stderr, flush=True)
        _HO_WARN_SHOWN = True
    yield

application = FastAPI(lifespan=_ho_lifespan{openapi_config})
application.include_router(router)
if _has_custom:
    application.include_router(_custom_router)
'''

OPENAPI_CONFIG = """, title="{title}", version="{version}" """

HO_META_ROUTE = (
    '\n@router.get("{version_prefix}/ho_meta")\n'
    'async def _crud_meta() -> dict:\n'
    '    return MODEL.ho_meta()\n'
)

HO_ACCESS_ROUTE = (
    '\n_STATIC_ACCESS_MAP = {json_str}\n'
    '\n_ACCESS_MAP = get_access_map()\n\n'
    '@router.get("{version_prefix}/ho_access")\n'
    'async def _crud_access_map(request: Request) -> dict:\n'
    '    authorized_roles = _get_roles(request)\n'
    '    return _filter_access_for_roles(_ACCESS_MAP, authorized_roles)\n'
)

HO_ROLES_ROUTE = (
    '\n_ROLES = {roles_json}\n\n'
    '@router.get("{version_prefix}/ho_roles")\n'
    'async def _crud_roles_list() -> list:\n'
    '    return _ROLES\n'
)

WS_HELPERS = """
import json as _json
from fastapi import WebSocket as _WS, WebSocketDisconnect as _WSD

class _ConnectionManager:
    def __init__(self):
        self._sockets: set = set()

    async def connect(self, ws: _WS) -> None:
        await ws.accept()
        self._sockets.add(ws)

    def disconnect(self, ws: _WS) -> None:
        self._sockets.discard(ws)

    async def broadcast(self, message: dict) -> None:
        dead = set()
        for s in set(self._sockets):
            try:
                await s.send_text(_json.dumps(message, default=str))
            except Exception:
                dead.add(s)
        self._sockets -= dead

_manager = _ConnectionManager()

@router.websocket("{version_prefix}/ws")
async def _ws_handler(ws: _WS) -> None:
    await _manager.connect(ws)
    try:
        while True:
            await ws.receive_text()
    except _WSD:
        pass
    finally:
        _manager.disconnect(ws)
"""

CRUD_GET_LIST = """
@router.get("{path}", description="{access_description}")
async def {handler_name}(
    request: Request,
{filter_params}    fields: Optional[List[str]] = None,
    limit: Optional[int] = 100,
    offset: Optional[int] = 0,
    q: Optional[str] = None,
) -> dict:
    api_excluded = getattr({module_alias}, 'API_EXCLUDED_FIELDS', [])
    roles = _get_roles(request)
    filter_kwargs = {{{filter_dict}}}

    # Parse 'q' parameter for search (format: col1:val1,col2:val2)
    # Values can start with comparison operators: >=, >, <=, <
    # Supports range syntax: >=val1<val2 or >val1<=val2
    search_cols = []
    range_filters = []  # Store range filters to apply after instance creation
    if q:
        import re
        for pair in q.split(','):
            if ':' in pair:
                col, val = pair.split(':', 1)
                col = col.strip()
                val = val.strip()
                if col and val and col not in api_excluded:
                    # Check for range syntax: >=val1<val2
                    range_match = re.match(r'^(>=|>)(.+?)(<=|<)(.+)$', val)
                    if range_match:
                        op1, operand1, op2, operand2 = range_match.groups()
                        operand1 = operand1.strip()
                        operand2 = operand2.strip()
                        if operand1 and operand2:
                            # Store both conditions to apply after instance creation
                            range_filters.append((col, op1, operand1, op2, operand2))
                    else:
                        # Check for single comparison operator at start
                        match = re.match(r'^(>=|>|<=|<)(.*)$', val)
                        if match:
                            op, operand = match.groups()
                            operand = operand.strip()
                            if operand:  # Only add filter if operand is not empty
                                filter_kwargs[col] = (op, operand)
                        else:
                            # Default: ilike with prefix matching
                            filter_kwargs[col] = ('ilike', val + '%')
                            search_cols.append(col)

    role_filter = _get_role_filter(getattr({module_alias}, 'CRUD_ACCESS', {{}}), "GET", roles)
    authorized = _effective_out_fields(getattr({module_alias}, 'CRUD_ACCESS', {{}}), "GET", roles, api_excluded)
    if fields:
        projection = [f for f in fields if not authorized or f in authorized]
    else:
        projection = authorized

    inst = {module_alias}.{class_name}(**{{**filter_kwargs, **role_filter}})

    # Apply range filters (must be done after instance creation)
    for col, op1, operand1, op2, operand2 in range_filters:
        field = getattr(inst, col)
        if op1 == '>=':
            field >= operand1
        else:  # op1 == '>'
            field > operand1
        if op2 == '<=':
            field <= operand2
        else:  # op2 == '<'
            field < operand2

    # Enable unaccent for search columns
    for col in search_cols:
        getattr(inst, col).unaccent = True

    data = await inst.ho_aselect(*projection, limit=limit, offset=offset)
    return {{
        "data": data,
        "meta": {{
            "offset": offset,
            "limit": limit,
            "has_more": len(data) == limit
        }}
    }}
"""

CRUD_GET_ONE = """
@router.get("{path}/{{id}}", description="{access_description}")
async def {handler_name}_get(
    request: Request,
    id: {pk_type_annotation},
) -> dict:
    api_excluded = getattr({module_alias}, 'API_EXCLUDED_FIELDS', [])
    roles = _get_roles(request)
    role_filter = _get_role_filter(getattr({module_alias}, 'CRUD_ACCESS', {{}}), "GET", roles)
    authorized = _effective_out_fields(getattr({module_alias}, 'CRUD_ACCESS', {{}}), "GET", roles, api_excluded)
    rows = await {module_alias}.{class_name}({pk_instance_filter}, **role_filter).ho_aselect(*authorized)
    if not rows:
        raise HTTPException(status_code=404)
    return rows[0]
"""

CRUD_POST = """
@router.post("{path}", description="{access_description}")
async def {handler_name}_create(
    request: Request,
    data: {in_typedict},
) -> dict:
    api_excluded = getattr({module_alias}, 'API_EXCLUDED_FIELDS', [])
    in_fields = _effective_in_fields(getattr({module_alias}, 'CRUD_ACCESS', {{}}), "POST", _get_roles(request), api_excluded)
    payload = {{k: v for k, v in data.model_dump(exclude_none=True).items() if not in_fields or k in in_fields}}
    result = await {module_alias}.{class_name}(**payload).ho_ainsert()
    await _manager.broadcast({{"event": "create", "resource": "{resource}", "id": {pk_broadcast_expr}}})
    return result
"""

CRUD_PUT = """
@router.put("{path}/{{id}}", description="{access_description}")
async def {handler_name}_update(
    request: Request,
    id: {pk_type_annotation},
    data: {in_typedict},
) -> dict:
    api_excluded = getattr({module_alias}, 'API_EXCLUDED_FIELDS', [])
    in_fields = _effective_in_fields(getattr({module_alias}, 'CRUD_ACCESS', {{}}), "PUT", _get_roles(request), api_excluded)
    payload = {{k: v for k, v in data.model_dump(exclude_none=True).items() if not in_fields or k in in_fields}}
    authorized = _effective_out_fields(getattr({module_alias}, 'CRUD_ACCESS', {{}}), "PUT", _get_roles(request), api_excluded)
    result = await {module_alias}.{class_name}({pk_instance_filter}).ho_aupdate(*(authorized or ['*']), **payload)
    if not result:
        raise HTTPException(status_code=404)
    await _manager.broadcast({{"event": "update", "resource": "{resource}", "id": id}})
    return result[0]
"""

CRUD_DELETE = """
@router.delete("{path}/{{id}}", description="{access_description}")
async def {handler_name}_delete(
    request: Request,
    id: {pk_type_annotation},
) -> None:
    await _ws_broadcast_cascade(
        {module_alias}.{class_name}({pk_instance_filter}), "{resource}", id
    )
    result = await {module_alias}.{class_name}({pk_instance_filter}).ho_adelete('*')
    if not result:
        raise HTTPException(status_code=404)
    await _manager.broadcast({{"event": "delete", "resource": "{resource}", "id": id}})
"""

WS_CASCADE_HELPER = """
_WS_RMAP: dict = {{
{resource_entries}
}}

async def _ws_broadcast_cascade(inst, resource: str, pk_val, _seen: set | None = None) -> None:
    if _seen is None:
        _seen = set()
    _key = (resource, str(pk_val))
    if _key in _seen:
        return
    _seen.add(_key)
    for _fk in inst._ho_fkeys.values():
        if not _fk.is_reverse or len(_fk.fk_names) != 1:
            continue
        _fk_field = _fk.fk_names[0]
        _fqtn     = _fk.remote['fqtn']
        _r        = f"{{_fqtn[0].replace('.', '_')}}/{{_fqtn[1]}}"
        if _r not in _WS_RMAP:
            continue
        _cls, _pk = _WS_RMAP[_r]
        for _row in await _cls(**{{_fk_field: pk_val}}).ho_aselect(_pk):
            _rid = _row[_pk]
            await _ws_broadcast_cascade(_cls(**{{_pk: _rid}}), _r, _rid, _seen)
            await _manager.broadcast({{"event": "delete", "resource": _r, "id": _rid}})
"""


def typedict_block(class_name: str, field_names: list, all_fields: dict) -> str:
    from half_orm_gen.crud_routes import _py_type_str
    lines = [f'class {class_name}(BaseModel):']
    valid = [(f, all_fields[f]) for f in field_names if f in all_fields]
    if not valid:
        lines.append('    pass')
    else:
        for fname, fobj in valid:
            lines.append(f'    {fname}: Optional[{_py_type_str(fobj.py_type)}] = None')
    return '\n'.join(lines)
