"""
Template strings for the generated api/app.py.
"""

HEADER = """\
# This file is generated by `half_orm litestar generate`. Do not edit by hand.
from typing import Union, Any, List, TypedDict
import datetime
import uuid
import os
import sys
import typing
from typing import Optional

cur_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, cur_dir)
par_dir = os.path.join(cur_dir, os.path.pardir)
sys.path.insert(0, par_dir)

from litestar import Request, Litestar, get, post, patch, put, delete, Response, MediaType
from litestar.exceptions import HTTPException
from litestar.status_codes import HTTP_500_INTERNAL_SERVER_ERROR
from litestar.logging import LoggingConfig
from litestar.openapi import OpenAPIConfig
from dataclasses import dataclass, field

from {module} import ho_baseclasses
from {module} import ho_typeddicts
from {module} import MODEL
from api import guards

try:
    from api.custom.routes import routes
except ImportError:
    routes = []

try:
    from api.custom.middlewares import middlewares
except ImportError:
    middlewares = []

try:
    from api.custom.middlewares.authorization import Authorization
    _auth_middleware = [Authorization]
except ImportError:
    _auth_middleware = []

logging_config = LoggingConfig(
    loggers={{
        "app": {{
            "level": "ERROR",
            "handlers": ["queue_listener"],
        }}
    }}
)

"""

FOOTER = """
async def _ho_startup() -> None:
    await MODEL.aconnect()

application = Litestar(
    route_handlers=[{route_handlers}] + routes,
    middleware=_auth_middleware + middlewares,
    logging_config=logging_config,
    on_startup=[_ho_startup],{openapi_config}
)
"""

OPENAPI_CONFIG = """
    openapi_config=OpenAPIConfig(title="{title}", version="{version}"),"""

# ---------------------------------------------------------------------------
# @api_* route templates
# ---------------------------------------------------------------------------

IMPORT = "\nfrom {schema} import {module_name} as {module_alias}\n"

GET = """
@get({litestar_args})
async def {full_name}({query_params}) -> typing.List[ho_baseclasses.{dc_name}]:
    return await {module_alias}.{class_name}().{name}({params})
"""

POST = """
@post({litestar_args})
async def {full_name}({query_params}) -> ho_baseclasses.{dc_name}:
    return await {module_alias}.{class_name}().{name}({params})
"""

PATCH = """
@patch({litestar_args})
async def {full_name}(request: "Request", data: ho_baseclasses.{dc_name}) -> ho_baseclasses.{dc_name}:
    return await {module_alias}.{class_name}().{name}({params})
"""

PUT = """
@put({litestar_args})
async def {full_name}(request: "Request", {path_params}) -> ho_baseclasses.{dc_name}:
    return await {module_alias}.{class_name}().{name}({params})
"""

DELETE = """
@delete({litestar_args})
async def {full_name}(request: "Request", {path_params}) -> None:
    return await {module_alias}.{class_name}().{name}({params})
"""

DIRECT_API = """
from {module_str} import {function} as {function_alias}
"""

HTTP = {
    'GET':    GET,
    'POST':   POST,
    'PATCH':  PATCH,
    'PUT':    PUT,
    'DELETE': DELETE,
}

# ---------------------------------------------------------------------------
# Auto-CRUD templates
# ---------------------------------------------------------------------------

CRUD_HELPERS = """
def _effective_out_fields(crud_access, verb, authorized_roles, api_excluded=None):
    api_excluded = api_excluded or []
    role_map = crud_access.get(verb, {})
    get_map = crud_access.get('GET', {})
    fields = []
    for role in authorized_roles:
        rv = role_map.get(role)
        if rv is None:
            return []
        if isinstance(rv, dict):
            if 'out' in rv:
                out = rv['out']
            else:
                get_rv = get_map.get(role)
                out = get_rv if not isinstance(get_rv, dict) else get_rv.get('out')
        else:
            out = rv
        if out is None:
            return []
        fields.extend(out)
    return [f for f in dict.fromkeys(fields) if f not in api_excluded]


def _effective_in_fields(crud_access, verb, authorized_roles, api_excluded=None):
    api_excluded = api_excluded or []
    role_map = crud_access.get(verb, {})
    fields = []
    for role in authorized_roles:
        rv = role_map.get(role)
        if rv is None or not isinstance(rv, dict):
            return []
        in_val = rv.get('in')
        if in_val is None:
            return []
        fields.extend(in_val)
    return [f for f in dict.fromkeys(fields) if f not in api_excluded]


def _filter_access_for_roles(access_map, authorized_roles):
    result = {}
    for resource, verbs in access_map.items():
        resource_entry = {}
        for verb, roles in verbs.items():
            if verb == 'DELETE':
                if any(r in roles and roles[r] == 'allowed' for r in authorized_roles):
                    resource_entry[verb] = True
            else:
                active = {r: roles[r] for r in authorized_roles if r in roles}
                if not active:
                    continue
                if verb == 'GET':
                    out = []
                    for v in active.values():
                        out.extend(v.get('out', []))
                    resource_entry[verb] = {'out': list(dict.fromkeys(out))}
                else:
                    in_f, out_f = [], []
                    for v in active.values():
                        in_f.extend(v.get('in', []))
                        out_f.extend(v.get('out', []))
                    resource_entry[verb] = {
                        'in':  list(dict.fromkeys(in_f)),
                        'out': list(dict.fromkeys(out_f)),
                    }
        if resource_entry:
            result[resource] = resource_entry
    return result

"""

CRUD_TYPEDICT = """
class {class_name}(TypedDict, total=False):
{fields}
"""

CRUD_MODULE_IMPORT = "\nfrom {schema} import {module_name} as {module_alias}\n"

CRUD_GET_LIST = """
@get("{path}", description="{access_description}")
async def {handler_name}(
    request: Request,
{filter_params}    fields: Optional[List[str]] = None,
    limit: Optional[int] = None,
    offset: Optional[int] = None,
) -> list[{out_typedict}]:
    api_excluded = getattr({module_alias}, 'API_EXCLUDED_FIELDS', [])
    filter_kwargs = {{{filter_dict}}}
    authorized = _effective_out_fields({module_alias}.CRUD_ACCESS, "GET", getattr(request.state, "authorized_roles", []), api_excluded)
    if fields:
        projection = [f for f in fields if not authorized or f in authorized]
    else:
        projection = authorized
    return await {module_alias}.{class_name}(**filter_kwargs).ho_aselect(
        *projection, limit=limit, offset=offset
    )
"""

CRUD_GET_ONE = """
@get("{path}/{{id: {pk_path_type}}}", description="{access_description}")
async def {handler_name}_get(
    request: Request,
    id: {pk_py_type},
) -> {out_typedict}:
    api_excluded = getattr({module_alias}, 'API_EXCLUDED_FIELDS', [])
    authorized = _effective_out_fields({module_alias}.CRUD_ACCESS, "GET", getattr(request.state, "authorized_roles", []), api_excluded)
    rows = await {module_alias}.{class_name}({pk_field}=id).ho_aselect(*authorized)
    if not rows:
        raise HTTPException(status_code=404)
    return rows[0]
"""

CRUD_POST = """
@post("{path}", description="{access_description}")
async def {handler_name}_create(
    request: Request,
    data: {in_typedict},
) -> {out_typedict}:
    api_excluded = getattr({module_alias}, 'API_EXCLUDED_FIELDS', [])
    in_fields = _effective_in_fields({module_alias}.CRUD_ACCESS, "POST", getattr(request.state, "authorized_roles", []), api_excluded)
    payload = {{k: v for k, v in dict(data).items() if v is not None and (not in_fields or k in in_fields)}}
    return await {module_alias}.{class_name}(**payload).ho_ainsert()
"""

CRUD_PUT = """
@put("{path}/{{id: {pk_path_type}}}", description="{access_description}")
async def {handler_name}_update(
    request: Request,
    id: {pk_py_type},
    data: {in_typedict},
) -> {out_typedict}:
    api_excluded = getattr({module_alias}, 'API_EXCLUDED_FIELDS', [])
    in_fields = _effective_in_fields({module_alias}.CRUD_ACCESS, "PUT", getattr(request.state, "authorized_roles", []), api_excluded)
    payload = {{k: v for k, v in dict(data).items() if v is not None and (not in_fields or k in in_fields)}}
    result = await {module_alias}.{class_name}({pk_field}=id).ho_aupdate(**payload)
    if not result:
        raise HTTPException(status_code=404)
    return result[0]
"""

CRUD_DELETE = """
@delete("{path}/{{id: {pk_path_type}}}", description="{access_description}")
async def {handler_name}_delete(
    request: Request,
    id: {pk_py_type},
) -> None:
    result = await {module_alias}.{class_name}({pk_field}=id).ho_adelete()
    if not result:
        raise HTTPException(status_code=404)
"""
