"""
Template strings for the generated api/app.py.
"""

HEADER = """\
# This file is generated by `half_orm litestar generate`. Do not edit by hand.
from typing import Union, Any, List
import datetime
import uuid
import os
import sys
import typing
from typing import Optional

cur_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, cur_dir)
par_dir = os.path.join(cur_dir, os.path.pardir)
sys.path.insert(0, par_dir)

from litestar import Request, Litestar, get, post, patch, put, delete, Response, MediaType
from litestar.exceptions import HTTPException
from litestar.status_codes import HTTP_500_INTERNAL_SERVER_ERROR
from litestar.logging import LoggingConfig
from litestar.openapi import OpenAPIConfig
from dataclasses import dataclass, field

from {module} import ho_baseclasses
from {module} import ho_typeddicts
from api import guards

try:
    from api.custom.routes import routes
except ImportError:
    routes = []

try:
    from api.custom.middlewares import middlewares
except ImportError:
    middlewares = []

try:
    from api.custom.middlewares.authorization import Authorization
    _auth_middleware = [Authorization]
except ImportError:
    _auth_middleware = []

logging_config = LoggingConfig(
    loggers={{
        "app": {{
            "level": "ERROR",
            "handlers": ["queue_listener"],
        }}
    }}
)

"""

FOOTER = """
application = Litestar(
    route_handlers=[{route_handlers}] + routes,
    middleware=_auth_middleware + middlewares,
    logging_config=logging_config,{openapi_config}
)
"""

OPENAPI_CONFIG = """
    openapi_config=OpenAPIConfig(title="{title}", version="{version}"),"""

# ---------------------------------------------------------------------------
# @api_* route templates
# ---------------------------------------------------------------------------

IMPORT = "\nfrom {schema} import {module_name} as {module_alias}\n"

GET = """
@get({litestar_args})
async def {full_name}({query_params}) -> typing.List[ho_baseclasses.{dc_name}]:
    return await {module_alias}.{class_name}().{name}({params})
"""

POST = """
@post({litestar_args})
async def {full_name}({query_params}) -> ho_baseclasses.{dc_name}:
    return await {module_alias}.{class_name}().{name}({params})
"""

PATCH = """
@patch({litestar_args})
async def {full_name}(request: "Request", data: ho_baseclasses.{dc_name}) -> ho_baseclasses.{dc_name}:
    return await {module_alias}.{class_name}().{name}({params})
"""

PUT = """
@put({litestar_args})
async def {full_name}(request: "Request", {path_params}) -> ho_baseclasses.{dc_name}:
    return await {module_alias}.{class_name}().{name}({params})
"""

DELETE = """
@delete({litestar_args})
async def {full_name}(request: "Request", {path_params}) -> None:
    return await {module_alias}.{class_name}().{name}({params})
"""

DIRECT_API = """
from {module_str} import {function} as {function_alias}
"""

HTTP = {
    'GET':    GET,
    'POST':   POST,
    'PATCH':  PATCH,
    'PUT':    PUT,
    'DELETE': DELETE,
}

# ---------------------------------------------------------------------------
# Auto-CRUD templates
# ---------------------------------------------------------------------------

CRUD_HELPERS = """
def _effective_fields(crud_access: dict, verb: str, authorized_roles: list) -> list:
    \"\"\"Union of allowed fields for all authorized roles.

    Returns [] if any role has None (no restriction = all fields).
    \"\"\"
    role_fields = crud_access.get(verb, {{}})
    if any(role_fields.get(r) is None for r in authorized_roles):
        return []
    return list({{f for r in authorized_roles for f in (role_fields.get(r) or [])}})


def _writable_fields(data: dict, crud_access: dict, verb: str, authorized_roles: list) -> dict:
    \"\"\"Filter incoming data dict to fields the authorized roles may write.\"\"\"
    allowed = _effective_fields(crud_access, verb, authorized_roles)
    if not allowed:
        return data
    return {{k: v for k, v in data.items() if k in allowed}}

"""

CRUD_MODULE_IMPORT = "\nfrom {schema} import {module_name} as {module_alias}\n"

CRUD_GET_LIST = """
@get("{path}", description="{access_description}")
async def {handler_name}(
    request: Request,
{filter_params}    fields: Optional[List[str]] = None,
    limit: Optional[int] = None,
    offset: Optional[int] = None,
) -> list[ho_typeddicts.{typedict_name}]:
    filter_kwargs = {{{filter_dict}}}
    authorized = _effective_fields({module_alias}.CRUD_ACCESS, "GET", getattr(request.state, "authorized_roles", []))
    if fields:
        projection = [f for f in fields if not authorized or f in authorized]
    else:
        projection = authorized
    return [
        row async for row in {module_alias}.{class_name}(**filter_kwargs).ho_aselect(
            *projection, limit=limit, offset=offset
        )
    ]
"""

CRUD_GET_ONE = """
@get("{path}/{{id: {pk_path_type}}}", description="{access_description}")
async def {handler_name}_get(
    request: Request,
    id: {pk_py_type},
) -> ho_typeddicts.{typedict_name}:
    authorized = _effective_fields({module_alias}.CRUD_ACCESS, "GET", getattr(request.state, "authorized_roles", []))
    rows = [row async for row in {module_alias}.{class_name}({pk_field}=id).ho_aselect(*authorized)]
    if not rows:
        raise HTTPException(status_code=404)
    return rows[0]
"""

CRUD_POST = """
@post("{path}", description="{access_description}")
async def {handler_name}_create(
    request: Request,
    data: ho_typeddicts.{typedict_name},
) -> ho_typeddicts.{typedict_name}:
    writable = _writable_fields(dict(data), {module_alias}.CRUD_ACCESS, "POST", getattr(request.state, "authorized_roles", []))
    return await {module_alias}.{class_name}(**writable).ho_ainsert()
"""

CRUD_PUT = """
@put("{path}/{{id: {pk_path_type}}}", description="{access_description}")
async def {handler_name}_update(
    request: Request,
    id: {pk_py_type},
    data: ho_typeddicts.{typedict_name},
) -> ho_typeddicts.{typedict_name}:
    payload = {{k: v for k, v in dict(data).items() if v is not None}}
    writable = _writable_fields(payload, {module_alias}.CRUD_ACCESS, "PUT", getattr(request.state, "authorized_roles", []))
    result = await {module_alias}.{class_name}({pk_field}=id).ho_aupdate(**writable)
    if not result:
        raise HTTPException(status_code=404)
    return result[0]
"""

CRUD_DELETE = """
@delete("{path}/{{id: {pk_path_type}}}", description="{access_description}")
async def {handler_name}_delete(
    request: Request,
    id: {pk_py_type},
) -> None:
    result = await {module_alias}.{class_name}({pk_field}=id).ho_adelete()
    if not result:
        raise HTTPException(status_code=404)
"""
